language: node_js
node_js:  
  - "16"  
install:  
  - npm install
script:  
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir:  dist
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: false
  name: Hbuilderx
  email: 285085215@qq.com
  on:
    branch: main